# Generated by Django 4.2.5 on 2023-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre poids', max_digits=5, null=True)),
                ('tour_de_taille', models.PositiveIntegerField(blank=True, help_text='Indiquez votre tour de taille en cm', null=True)),
                ('frequence_cardiaque', models.PositiveIntegerField(blank=True, help_text='Indiquez votre fréquence cardiaque par minute', null=True)),
                ('tension_arterielle_systolique_matin', models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle systolique (prise du matin)', null=True)),
                ('tension_arterielle_systolique_soir', models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle systolique (prise du soir)', null=True)),
                ('tension_arterielle_diastolique_matin', models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle diastolique (prise du matin)', null=True)),
                ('tension_arterielle_diastolique_soir', models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle diastolique (prise du soir)', null=True)),
                ('symptomes_cardiovasculaires', models.TextField(blank=True, help_text='Décrivez vos symptômes cardiovasculaires en quelques mots', null=True)),
                ('nombre_medicaments_jour', models.PositiveIntegerField(blank=True, help_text='Indiquez le nombre de médicaments pris dans la journée', null=True)),
                ('oublie_medicament_matin', models.BooleanField(default=False, help_text='Oublie de prendre le(s) médicament(s) le matin')),
                ('oublie_medicament_soir', models.BooleanField(default=False, help_text='Oublie de prendre le(s) médicament(s) le soir')),
                ('effets_secondaires_remarques', models.BooleanField(default=False, help_text='Effet(s) secondaire(s) remarqué(s)')),
                ('symptomes_particuliers_remarques', models.BooleanField(default=False, help_text='Symptôme(s) particulier(s) remarqué(s)')),
                ('effets_secondaires_description', models.TextField(blank=True, help_text='Décrivez vos effets secondaires et/ou symptômes particuliers remarqués en quelques mots', null=True)),
                ('consommation_alcool', models.BooleanField(default=False, help_text="Consommation d'alcool")),
                ('grignotage_sucre', models.BooleanField(default=False, help_text='Grignotage sucré')),
                ('grignotage_sale', models.BooleanField(default=False, help_text='Grignotage salé')),
                ('nombre_repas_jour', models.PositiveIntegerField(blank=True, help_text='Indiquez le nombre de repas pris durant la journée', null=True)),
                ('quantite_eau_bue_litres', models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez la quantité d'eau bu aujourd'hui", max_digits=5, null=True)),
                ('quantite_alcool_consomme_litres', models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez la quantité d'alcool bu aujourd'hui", max_digits=5, null=True)),
                ('activite_physique', models.BooleanField(default=False, help_text="J'ai eu une activité physique aujourd'hui")),
                ('nature_activite_physique', models.CharField(blank=True, help_text='Décrivez la nature de votre activité physique', max_length=200, null=True)),
                ('duree_activite_physique_minutes', models.PositiveIntegerField(blank=True, help_text='Indiquez la durée de votre activité physique en minutes', null=True)),
                ('presence_dyspnee', models.BooleanField(default=False, help_text='Présence de dyspnée')),
                ('presence_oedeme', models.BooleanField(default=False, help_text="Présence d'œdème")),
                ('presence_fievre', models.BooleanField(default=False, help_text='Présence de fièvre')),
                ('presence_palpitation', models.BooleanField(default=False, help_text='Présence de palpitation')),
                ('presence_douleur_thoracique', models.BooleanField(default=False, help_text='Présence de douleur thoracique')),
                ('presence_malaise', models.BooleanField(default=False, help_text='Présence de malaise')),
                ('heure_debut_palpitations', models.TimeField(blank=True, help_text="Indiquez l'heure de début des palpitations", null=True)),
                ('duree_total_palpitations_minutes', models.PositiveIntegerField(blank=True, help_text='Indiquez la durée totale des palpitations apparues durant la journée en minutes', null=True)),
                ('heure_debut_douleurs_thoraciques', models.TimeField(blank=True, help_text="Indiquez l'heure de début des douleurs thoraciques", null=True)),
                ('duree_total_douleurs_thoraciques_minutes', models.PositiveIntegerField(blank=True, help_text='Indiquez la durée totale des douleurs thoraciques apparues durant la journée en minutes', null=True)),
                ('heure_debut_malaises', models.TimeField(blank=True, help_text="Indiquez l'heure de début des malaises", null=True)),
                ('duree_total_malaises_minutes', models.PositiveIntegerField(blank=True, help_text='Indiquez la durée totale des malaises apparus durant la journée en minutes', null=True)),
                ('natremie_mmol_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de natremie en mmol/l (millimoles par litre)', max_digits=6, null=True)),
                ('potassium_mmol_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de potassium en mmol/l (millimoles par litre)', max_digits=6, null=True)),
                ('creatinine_umol_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de créatinine en umol/l (micromoles per litre)', max_digits=6, null=True)),
                ('clairance_creatinine_ml_per_min', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de clairance de créatinine en ml/min (millilitres per minute)', max_digits=6, null=True)),
                ('nt_probnp_ng_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de NT Probnp en ng/l (nanogrammes par litre)', max_digits=6, null=True)),
                ('fer_serique_mg_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de fer sérique mg/l (milligrame par litre)', max_digits=6, null=True)),
                ('hemoglobine_g_per_100_ml', models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez votre taux d'hémoglobine en g/100 ml (gramme par 100 millilitre)", max_digits=6, null=True)),
                ('vitesse_sedimentation_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de Vitesse de sédimentation (VS) en milimètre', max_digits=6, null=True)),
                ('proteine_c_reactive_mg_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux protéine C réactive en mg/l', max_digits=6, null=True)),
                ('troponine_jug_per_l', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de troponine en jug/l (microgrammes par litre)', max_digits=6, null=True)),
                ('vitamine_d_ng_per_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de vitamine D en ng/ml de sang', max_digits=6, null=True)),
                ('acide_urique_mg_per_l', models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez votre taux d'acide urique en mg/l", max_digits=6, null=True)),
                ('inr', models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de INR (International Normalized Ratio)', max_digits=6, null=True)),
            ],
        ),
    ]
