# Generated by Django 4.2.5 on 2023-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_userhealthdata_acide_urique_mg_per_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthdata',
            name='acide_urique_mg_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez votre taux d'acide urique en mg/l", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='activite_physique',
            field=models.BooleanField(default=False, help_text="J'ai eu une activité physique aujourd'hui"),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='clairance_creatinine_ml_per_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de clairance de créatinine en ml/min (millilitres per minute)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='consommation_alcool',
            field=models.BooleanField(default=False, help_text="Consommation d'alcool"),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='creatinine_umol_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de créatinine en umol/l (micromoles per litre)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='duree_activite_physique_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez la durée de votre activité physique en minutes', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='duree_total_douleurs_thoraciques_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez la durée totale des douleurs thoraciques apparues durant la journée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='duree_total_malaises_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez la durée totale des malaises apparus durant la journée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='duree_total_palpitations_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez la durée totale des palpitations apparues durant la journée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='effets_secondaires_description',
            field=models.TextField(blank=True, help_text='Décrivez vos effets secondaires et/ou symptômes particuliers remarqués en quelques mots', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='effets_secondaires_remarques',
            field=models.BooleanField(default=False, help_text='Effet(s) secondaire(s) remarqué(s)'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='fer_serique_mg_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de fer sérique mg/l (milligrame par litre)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='frequence_cardiaque',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez votre fréquence cardiaque par minute', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='grignotage_sale',
            field=models.BooleanField(default=False, help_text='Grignotage salé'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='grignotage_sucre',
            field=models.BooleanField(default=False, help_text='Grignotage sucré'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='hemoglobine_g_per_100_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez votre taux d'hémoglobine en g/100 ml (gramme par 100 millilitre)", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='heure_debut_douleurs_thoraciques',
            field=models.TimeField(blank=True, help_text="Indiquez l'heure de début des douleurs thoraciques", null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='heure_debut_malaises',
            field=models.TimeField(blank=True, help_text="Indiquez l'heure de début des malaises", null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='heure_debut_palpitations',
            field=models.TimeField(blank=True, help_text="Indiquez l'heure de début des palpitations", null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de INR (International Normalized Ratio)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='natremie_mmol_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de natremie en mmol/l (millimoles par litre)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='nature_activite_physique',
            field=models.CharField(blank=True, help_text='Décrivez la nature de votre activité physique', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='nombre_medicaments_jour',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez le nombre de médicaments pris dans la journée', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='nombre_repas_jour',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez le nombre de repas pris durant la journée', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='nt_probnp_ng_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de NT Probnp en ng/l (nanogrammes par litre)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='oublie_medicament_matin',
            field=models.BooleanField(default=False, help_text='Oublie de prendre le(s) médicament(s) le matin'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='oublie_medicament_soir',
            field=models.BooleanField(default=False, help_text='Oublie de prendre le(s) médicament(s) le soir'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='potassium_mmol_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de potassium en mmol/l (millimoles par litre)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='presence_douleur_thoracique',
            field=models.BooleanField(default=False, help_text='Présence de douleur thoracique'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='presence_dyspnee',
            field=models.BooleanField(default=False, help_text='Présence de dyspnée'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='presence_fievre',
            field=models.BooleanField(default=False, help_text='Présence de fièvre'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='presence_malaise',
            field=models.BooleanField(default=False, help_text='Présence de malaise'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='presence_oedeme',
            field=models.BooleanField(default=False, help_text="Présence d'œdème"),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='presence_palpitation',
            field=models.BooleanField(default=False, help_text='Présence de palpitation'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='proteine_c_reactive_mg_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux protéine C réactive en mg/l', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='quantite_alcool_consomme_litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez la quantité d'alcool bu aujourd'hui", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='quantite_eau_bue_litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Indiquez la quantité d'eau bu aujourd'hui", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='symptomes_cardiovasculaires',
            field=models.TextField(blank=True, help_text='Décrivez vos symptômes cardiovasculaires en quelques mots', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='symptomes_particuliers_remarques',
            field=models.BooleanField(default=False, help_text='Symptôme(s) particulier(s) remarqué(s)'),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='tension_arterielle_diastolique_matin',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle diastolique (prise du matin)', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='tension_arterielle_diastolique_soir',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle diastolique (prise du soir)', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='tension_arterielle_systolique_matin',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle systolique (prise du matin)', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='tension_arterielle_systolique_soir',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez votre Tension artérielle systolique (prise du soir)', null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='troponine_jug_per_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de troponine en jug/l (microgrammes par litre)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='vitamine_d_ng_per_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez votre taux de vitamine D en ng/ml de sang', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='vitesse_sedimentation_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez vos valeurs de Vitesse de sédimentation (VS) en milimètre', max_digits=6, null=True),
        ),
    ]
