# Generated by Django 4.2.5 on 2023-10-20 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_userhealthdata_acide_urique_mg_per_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthdata',
            name='date_remplissage',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userhealthdata',
            name='periodicite_jours',
            field=models.IntegerField(null=True),
        ),
    ]
