# Generated by Django 4.2.5 on 2023-11-13 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_remove_userhealthdata_acide_urique_mg_per_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_remplissage', models.DateField(auto_now=True)),
                ('periodicite_jours', models.IntegerField(null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('irritability', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Irritability score (0, 1, 5, 10)')),
                ('feelings_of_depression', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Feelings of depression score (0, 1, 5, 10)')),
                ('dry_mouth_or_sore_throat', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Dry mouth or sore throat score (0, 1, 5, 10)')),
                ('impulsive_actions_or_gestures', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Impulsive actions or gestures score (0, 1, 5, 10)')),
                ('teeth_grinding', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Teeth grinding score (0, 1, 5, 10)')),
                ('difficulty_staying_seated', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Difficulty staying seated score (0, 1, 5, 10)')),
                ('nightmares', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Nightmares score (0, 1, 5, 10)')),
                ('diarrhea', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (5, '5'), (10, '10')], default=0, help_text='Diarrhea score (0, 1, 5, 10)')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
